services:
  mongodb:
    image: mongo:7
    container_name: supfile-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: supfile-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/utils:/app/utils
      - C:/supfile_shared_storage:/app/storage
      - /app/node_modules
    depends_on:
      - mongodb
    restart: unless-stopped
    command: npm start


  frontend:
    build: ./frontend
    container_name: supfile-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
